### ISSUE TITLE
Changing nodes colors

### ISSUE THREAD

**Issue by galuel** [ucoin-io/sakia#348]
![ucoin](https://cloud.githubusercontent.com/assets/5245398/12290166/7d41c0e0-b9e0-11e5-994a-7bffe1a2444d.png)

When we sort nodes in the nodes tab, it appears that "consensus" is green, and near consensus is orange.

It's ok, but here we can see that nodes are with n° of blocks > green n° ones with orange, as well as nodes with n° of blocks < green n°

I suggest to [add a new color](http://www.toutes-les-couleurs.com/couleurs-complementaires.php) : Purple > Green > Orange

**Comment by Insoleet** [comment]
I'm not sure why you want to sort nodes based on the block number ? The consensus is more important, since block number doesn't mean anything really. (High blocks are not necessary in the main branch, nodes could have forked...)

I think this problem won't be present when we use websocket in sakia, since the view of the network will then be instantaneous.

**Comment by galuel** [comment]
"High blocks are not necessary in the main branch", but high blocks differ from low ones.

**Comment by c-geek** [comment]
The "orange" and "high blocks" we see in this screenshot are a mirage, the reality is already far away, and is green.

The solution would probably be that Sakia reflects better the reality than adding colors to say "the reality is coming".
